### ISSUE TITLE
Timezone "W-SU" missing

### ISSUE THREAD

**Issue by Kishinskiy** [modernuo/ModernUO#1385]
I have error  message when I try start server, after select Ages I get error message:

[15:20:04 INF] Automatically detected client version 7.0.98.1 <s:Server.UOClient>
Error:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Collections.Generic.KeyNotFoundException: The given key 'W-SU' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Server.TimeZoneHandler.Configure() in /Users/olegkishinskiy/ModernUO-0.9.6-2.150/Projects/Server/TimeZones/TimeZoneHandler.cs:line 76
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Server.AssemblyHandler.Invoke(String method) in /Users/olegkishinskiy/ModernUO-0.9.6-2.150/Projects/Server/AssemblyHandler.cs:line 148
   at Server.Core.Main(String[] args) in /Users/olegkishinskiy/ModernUO-0.9.6-2.150/Projects/Server/Main.cs:line 511
This exception is fatal, press return to exit

System: macOS 12.6.4
.NET 7.0.4
client version 7.0.98.1

**Comment by kamronbatman** [comment]
It looks like my [timezone data file](https://github.com/modernuo/ModernUO/blob/3c86af4ff393d5ab405c20e0882d2837a737a027/Distribution/Data/timezones.json#L681) doesn't support the Moscow alias timezone.
In that file, try adding `"W-SU",` below `"Europe/Moscow",` and let me know if that fixes the issue.

**Comment by kamronbatman** [comment]
@Kishinskiy can you please test PR #1388 to see if it fixes your issue?
