### ISSUE TITLE
GenerateSpawners JSON crash

### ISSUE THREAD

**Issue by jabinb** [modernuo/ModernUO#185]
When attempting to load one of the distribution json spawner files the server will crash with the following, e.g. `[generatespawners felucca.json`

```
System.Text.Json.JsonException: The JSON value could not be converted to System.Collections.Generic.List`1[Server.Json.DynamicJson]. Path: $ | LineNumber: 0 | BytePositionInLine: 1.
   at System.Text.Json.ThrowHelper.ThrowJsonException_DeserializeUnableToConvertValue(Type propertyType)
   at System.Text.Json.JsonSerializer.HandleStartObject(JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   at System.Text.Json.JsonSerializer.ReadCore(Type returnType, JsonSerializerOptions options, Utf8JsonReader& reader)
   at System.Text.Json.JsonSerializer.Deserialize(String json, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at Server.Json.JsonConfig.Deserialize[T](String filePath, JsonSerializerOptions options) in /home/jabin/sources/ModernUO/Projects/Server/JsonConfiguration/JsonConfig.cs:line 60
   at Server.Engines.Spawners.GenerateSpawners.GenerateSpawners_OnCommand(CommandEventArgs e) in /home/jabin/sources/ModernUO/Projects/UOContent/Engines/Spawners/GenerateSpawners.cs:line 45
   at Server.CommandSystem.Handle(Mobile from, String text, MessageType type) in /home/jabin/sources/ModernUO/Projects/Server/Commands.cs:line 222
   at Server.Mobile.DoSpeech(String text, Int32[] keywords, MessageType type, Int32 hue) in /home/jabin/sources/ModernUO/Projects/Server/Mobile.cs:line 4866
   at Server.Mobiles.PlayerMobile.DoSpeech(String text, Int32[] keywords, MessageType type, Int32 hue) in /home/jabin/sources/ModernUO/Projects/UOContent/Mobiles/PlayerMobile.cs:line 1998
   at Server.Network.PacketHandlers.UnicodeSpeech(NetState state, PacketReader pvSrc) in /home/jabin/sources/ModernUO/Projects/Server/Network/PacketHandlers.cs:line 1324
   at Server.Network.MessagePumpService.DoWork() in /home/jabin/sources/ModernUO/Projects/Server/Network/MessagePumpService.cs:line 52
   at Server.Core.RunEventLoop(IMessagePumpService messagePumpService) in /home/jabin/sources/ModernUO/Projects/Server/Main.cs:line 424
```

However loading the `region-spawners.json` works fine.

**Comment by jabinb** [comment]
@kamronbatman I'll make a PR for this one

**Comment by kamronbatman** [comment]
Thanks for the PR.
I'll get the actual command format because it supports globs and a specific path set.
