### ISSUE TITLE
Crash in BitConverter

### ISSUE THREAD

**Issue by x0r00** [modernuo/ModernUO#347]
ystem.AggregateException: One or more errors occurred. (Destination array is not long enough to copy all the items in the collection. Check array index and length. (Parameter 'value'))
 ---> System.ArgumentException: Destination array is not long enough to copy all the items in the collection. Check array index and length. (Parameter 'value')
   at System.BitConverter.ToInt64(Byte[] value, Int32 startIndex)
   at Server.Utility.GetLongAddressValue(IPAddress address) in D:\UOWORK\ModernUO\Projects\Server\Utilities\Utility.cs:line 1060
   at Server.BufferWriter.Write(IPAddress value) in D:\UOWORK\ModernUO\Projects\Server\Serialization\BufferWriter.cs:line 179
   at Server.Items.RaffleEntry.Serialize(IGenericWriter writer) in D:\UOWORK\ModernUO\Projects\UOContent\Items\Special\House Raffle\HouseRaffleStone.cs:line 51
   at Server.Items.HouseRaffleStone.Serialize(IGenericWriter writer) in D:\UOWORK\ModernUO\Projects\UOContent\Items\Special\House Raffle\HouseRaffleStone.cs:line 617
   at Server.Item.Serialize() in D:\UOWORK\ModernUO\Projects\Server\Items\Item.cs:line 809
   at Server.World.<>c__DisplayClass64_0`1.<SaveEntities>b__0(T t) in D:\UOWORK\ModernUO\Projects\Server\World\World.cs:line 563
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Server.World.SaveEntities[T](IEnumerable`1 list, DateTime serializeStart) in D:\UOWORK\ModernUO\Projects\Server\World\World.cs:line 557

**Comment by kamronbatman** [comment]
Thanks I'll take a look!

**Comment by kamronbatman** [comment]
@x0r00 looks like IPv6 support is going to be complicated, especially since we currently allow firewalling with a loose wildcard/range syntax, e.g.:
`192.*.10-200.?` or something like that.

I could drop support for this syntax, but I think people will be kind of upset. Unfortunately parsing IPv6 by itself is pretty tough, furthermore supporting that syntax is very tedious and tricky. I'll give it a shot, but will need to be patient. Sorry if this is inconvenient!
