### ISSUE TITLE
Crash Serialization on save

### ISSUE THREAD

**Issue by x0r00** [modernuo/ModernUO#349]
System.AggregateException: One or more errors occurred. (Index was outside the bounds of the array.)
 ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Server.BufferWriter.WriteEncodedInt(Int32 value) in D:\UOWORK\ModernUO\Projects\Server\Serialization\BufferWriter.cs:line 104
   at Server.Item.Serialize(IGenericWriter writer) in D:\UOWORK\ModernUO\Projects\Server\Items\Item.cs:line 1022
   at Server.Items.LaderStone.Serialize(IGenericWriter writer) in D:\UOWORK\ModernUO\Projects\UOContent\SpecialSystems\Items\Stones\LaderStone.cs:line 31
   at Server.Item.Serialize() in D:\UOWORK\ModernUO\Projects\Server\Items\Item.cs:line 809
   at Server.World.<>c__DisplayClass64_0`1.<SaveEntities>b__0(T t) in D:\UOWORK\ModernUO\Projects\Server\World\World.cs:line 563
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Server.World.SaveEntities[T](IEnumerable`1 list, DateTime serializeStart) in D:\UOWORK\ModernUO\Projects\Server\World\World.cs:line 557
   at Server.World.Save() in D:\UOWORK\ModernUO\Projects\Server\World\World.cs:line 607
   at Server.Misc.AutoSave.Save() in D:\UOWORK\ModernUO\Projects\UOContent\Misc\AutoSave.cs:line 103
   at Server.Misc.AutoSave.OnTick() in D:\UOWORK\ModernUO\Projects\UOContent\Misc\AutoSave.cs:line 52
   at Server.Timer.Slice() in D:\UOWORK\ModernUO\Projects\Server\Timer\Timer.cs:line 152
   at Server.Core.RunEventLoop() in D:\UOWORK\ModernUO\Projects\Server\Main.cs:line 483

fixed Serialization  in on another project
https://github.com/ServUO/ServUO/pull/1565/commits/159f88514bf645abe90db6cfe6b0931c422918a8

**Comment by kamronbatman** [comment]
Thanks I'll take a look! Should be able to fix this today.

**Comment by kamronbatman** [comment]
@x0r00 I am not sure if those line numbers are correct. Can you make sure you are running it in debug mode and see if you can get it to crash again? You can also contact me on Discord.
To publish in debug mode, do:
> publish.cmd Debug

**Comment by kamronbatman** [comment]
@x0r00 I am not sure if the PR I made will fix the issue. It looks like it might? I am going to push the code, and if you could test and replicate the same crash, that would be great. If you continue to have the same crash, then we should get together and investigate further on your shard.

Thank you for the help!

**Comment by x0r00** [comment]
> @x0r00 I am not sure if those line numbers are correct. Can you make sure you are running it in debug mode and see if you can get it to crash again? You can also contact me on Discord (Mr.Batman#3572)
> To publish in debug mode, do:
> 
> > publish.cmd Debug
> 
> EDIT: I also may need to see your `LaderStone.cs` file.

I got this crash for random Item while keeping serialization, servuo had the same problem. https://www.servuo.com/threads/server-crash-at-save.6459/

**Comment by kamronbatman** [comment]
Hi @x0r00, that issue on ServUO was due to a different cause. Can you get onto discord so we can investigate further?

**Comment by x0r00** [comment]
> Hi @x0r00, that issue on ServUO was due to a different cause. Can you get onto discord so we can investigate further?
Sure

**Comment by x0r00** [comment]
Now, Server is stable for 4day.
