### ISSUE TITLE
Crash: Post unicode symbols into a bulletin board message

### ISSUE THREAD

**Issue by jabinb** [modernuo/ModernUO#469]
When inputting the text `测试` (test in chinese) into a new post and them submitting it the server will crash with an `OutOfMemoryException`

```
System.OutOfMemoryException: Insufficient memory to continue the execution of the program.
   at Server.Network.BulletinBoardPackets.BBPostMessage(Mobile from, BaseBulletinBoard board, CircularBufferReader reader) in /sources/ModernUO/Projects/UOContent/Items/Bulletin Boards/BulletinBoardPackets.cs:line 150
   at Server.Network.BulletinBoardPackets.BBClientRequest(NetState state, CircularBufferReader reader, Int32& packetLength) in /sources/ModernUO/Projects/UOContent/Items/Bulletin Boards/BulletinBoardPackets.cs:line 71
   at Server.Network.IncomingPackets.ProcessPacket(NetState ns, ArraySegment`1[] buffer) in /sources/ModernUO/Projects/Server/Network/Packets/IncomingPackets.cs:line 163
   at Server.Network.NetState.HandleReceive() in /sources/ModernUO/Projects/Server/Network/NetState/NetState.cs:line 628
```

**Comment by kamronbatman** [comment]
I specifically checked chinese characters too lol

**Comment by kamronbatman** [comment]
This is an interesting one. The EA client has a bug where it doesn't send the entire string for the subject (it's buggy). CUO has a bug where it sends the wrong _byte length_, causing this crash.
See here for details regarding CUO:
https://discord.com/channels/458277173208547350/674900239421014016/810691000233754624

As of right now, this no longer crashes the server and instead writes out to network-errors.log.
