### ISSUE TITLE
SignGen command crash

### ISSUE THREAD

**Issue by kamronbatman** [modernuo/ModernUO#75]
Using [signgen crashes the shard

```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Server.Commands.SignParser.Parse(Mobile from) in Y:\Repositories\ModernUO\Projects\Scripts\Commands\SignParser.cs:line 25
   at Server.Commands.SignParser.SignGen_OnCommand(CommandEventArgs c) in Y:\Repositories\ModernUO\Projects\Scripts\Commands\SignParser.cs:line 21
   at Server.CommandSystem.Handle(Mobile from, String text, MessageType type) in Y:\Repositories\ModernUO\Projects\Server\Commands.cs:line 217
   at Server.Mobile.DoSpeech(String text, Int32[] keywords, MessageType type, Int32 hue) in Y:\Repositories\ModernUO\Projects\Server\Mobile.cs:line 4903
   at Server.Mobiles.PlayerMobile.DoSpeech(String text, Int32[] keywords, MessageType type, Int32 hue) in Y:\Repositories\ModernUO\Projects\Scripts\Mobiles\PlayerMobile.cs:line 1999
   at Server.Network.PacketHandlers.UnicodeSpeech(NetState state, PacketReader pvSrc) in Y:\Repositories\ModernUO\Projects\Server\Network\PacketHandlers.cs:line 1340
   at Server.Network.MessagePump.DoWork() in Y:\Repositories\ModernUO\Projects\Server\Network\MessagePump.cs:line 58
   at Server.Core.Main(String[] args) in Y:\Repositories\ModernUO\Projects\Server\Main.cs:line 482
```

**Comment by 3HMonkey** [comment]
Maybe you had just a typo while conversion. See https://github.com/modernuo/ModernUO/pull/81 for the fix.
