### ISSUE TITLE
GenStealArties command crashes the server

### ISSUE THREAD

**Issue by 3HMonkey** [modernuo/ModernUO#773]
`Server Crash Report
===================

ModernUO Version 0.8, Build 2.187
Operating System: Microsoft Windows NT 10.0.14393.0
.NET Framework: 5.0.9
Time: 2021-09-07-14-27-31
Mobiles: 16190
Items: 136703
Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Server.Items.StealableArtifactsSpawner.StealableEntry.CreateInstance() in C:\Users\wewan\Documents\GitHub\DefianceUOR\Projects\UOContent\Items\Decoration Artifacts\StealableArtifactsSpawner.cs:line 366
   at Server.Items.StealableArtifactsSpawner.StealableInstance.CheckRespawn() in C:\Users\wewan\Documents\GitHub\DefianceUOR\Projects\UOContent\Items\Decoration Artifacts\StealableArtifactsSpawner.cs:line 429
   at Server.Items.StealableArtifactsSpawner.CheckRespawn() in C:\Users\wewan\Documents\GitHub\DefianceUOR\Projects\UOContent\Items\Decoration Artifacts\StealableArtifactsSpawner.cs:line 276
   at Server.Timer.DelayCallTimer.OnTick() in C:\Users\wewan\Documents\GitHub\DefianceUOR\Projects\Server\Timer\Timer.DelayCall.cs:line 143
   at Server.Timer.Execute(Timer timer) in C:\Users\wewan\Documents\GitHub\DefianceUOR\Projects\Server\Timer\Timer.TimerWheel.cs:line 118
   at Server.Timer.Turn() in C:\Users\wewan\Documents\GitHub\DefianceUOR\Projects\Server\Timer\Timer.TimerWheel.cs:line 94
   at Server.Timer.Slice(Int64 tickCount) in C:\Users\wewan\Documents\GitHub\DefianceUOR\Projects\Server\Timer\Timer.TimerWheel.cs:line 55
   at Server.Core.RunEventLoop() in C:\Users\wewan\Documents\GitHub\DefianceUOR\Projects\Server\Main.cs:line 502`

**Comment by kamronbatman** [comment]
I can't replicate it by just running the command. Since it's random, I'll set the spawn time to something really low and just let the spawner run, maybe it will crash eventually.

Meanwhile, if you can replicate it, please add logging so we know wha type is null when we try to construct it.

**Comment by kamronbatman** [comment]
```cs
        [Constructible]
        public TreeStump(int itemID)
        {
            AddComponent(new AddonComponent(itemID), 0, 0, 0);

            Timer.StartTimer(TimeSpan.FromDays(1), TimeSpan.FromDays(1), GiveLogs, out _timerToken);
        }
```

You are using a custom item as an artifact that doesn't have an empty constructor.
I'll probably replace the spawner with an actual spawner so there is better logging.
